### ISSUE TITLE
Could you please include the dfmod file?

### ISSUE THREAD

**Issue by CHJ85** [TheLacus/vibrantwind-du-mod#1]
Hi there. I've been trying to find the dfmod file?
Not really sure how to compile this from source.
I checked your post on the DF forum, but the only download link there is the Real Grass mod.

**Comment by rossipaolo** [comment]
Hi, sorry for the late reply. Download is available on [nexus mods](https://www.nexusmods.com/daggerfallunity/mods/20?tab=files) under optional files.

**Comment by CHJ85** [comment]
Thanks a bunch! 👍
